# Generated by Django 3.1.2 on 2020-11-02 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 2, 13, 36, 56, 529992)),
        ),
    ]
