# Generated by Django 3.1.2 on 2020-10-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201024_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
