# Generated by Django 3.1.2 on 2020-10-28 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='percentage',
            new_name='funcionario',
        ),
    ]
