# Generated by Django 3.1.2 on 2020-10-28 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20201028_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='funcionario',
            new_name='employee',
        ),
    ]
