# Generated by Django 3.1.2 on 2020-11-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20201101_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='active',
            field=models.BooleanField(blank=True),
        ),
    ]
