# Generated by Django 3.1.2 on 2020-11-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20201101_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
