# Generated by Django 3.1.2 on 2020-11-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='company',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
    ]
