# Generated by Django 3.1.2 on 2020-11-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_amount'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='product_id',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
