# Generated by Django 3.1.2 on 2020-11-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20201108_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount',
        ),
    ]
